### ISSUE TITLE
Line numbers in output should be one-based

### ISSUE THREAD

**Issue by krahlro-sick** [mristin/opinionated-csharp-todos#4]
If the check fails, `record.Line` is printed to stdout ([`Program.cs:142`](https://github.com/mristin/opinionated-csharp-todos/blob/master/src/OpinionatedCsharpTodos/Program.cs#L142)).  This property is zero-based ([`Inspection.cs:27`](https://github.com/mristin/opinionated-csharp-todos/blob/master/src/OpinionatedCsharpTodos/Inspection.cs#L27)).  But the output should be one-based instead as line numbers typically start at 1.

**Comment by mristin** [comment]
Thanks @krahlro-sick for reporting the issues #4, #5 and #6! I fixed them and bumped the version to the pre-release 1.0.0-pre2.
